module Hedgehog.Plutus.Model (
  Tx (..),
  BalancedTx,
  TxIn (..),
  TxOut (..),
  Script (..),
  InScript (..),
  ScriptSource (..),
  TxContext (..),
  ScriptPurpose (..),
  Spend (..),
  balanceTx,
  forgetBlanced,
  balanceTxAsPubKey,
  balanceTxWhere,
  confirmBalanced,
  spendWhere,
  payToUser,
  payToScript,
  spendPubKeyUtxo,
  spendScriptOutput,
  mintWithRed,
  scriptPurposeTx,
  submitTx,
  submitBalancedTx,
)
where

import Hedgehog.Plutus.Model.Internal (
  BalancedTx,
  InScript (InScript, inScriptData, inScriptSource),
  Script (Script, unScript),
  ScriptPurpose (Minting, Spending),
  ScriptSource (InTransaction, RefScript),
  Spend (Spend, excess, spendUtxos),
  Tx (Tx, txExtraSignatures, txFee, txInputs, txMint, txOutputs, txValidRange),
  TxContext (TxContext, datums, interestingScripts, mockchain),
  TxIn (TxIn, txInRef, txInScript),
  TxOut (TxOut, txOutAddress, txOutDatum, txOutReferenceScript, txOutValue),
  balanceTx,
  balanceTxAsPubKey,
  balanceTxWhere,
  confirmBalanced,
  forgetBlanced,
  scriptPurposeTx,
  spendWhere,
 )
import Hedgehog.Plutus.Model.Run (
  submitBalancedTx,
  submitTx,
 )
import Hedgehog.Plutus.Model.TxHelpers (
  mintWithRed,
  payToScript,
  payToUser,
  spendPubKeyUtxo,
  spendScriptOutput,
 )
